base_model = "meta/llama-3.3-70b-instruct"
release_date = "2026-04-30"
last_updated = "2026-07-22"
attachment = false

[cost]
input = 0.638
output = 0.768
cache_write = 0.319

[limit]
output = 12_800
