base_model = "google/gemini-3.1-flash-lite"
name = "Gemini 3.1 Flash Lite (EU)"

[[reasoning_options]]
type = "effort"
values = ["none", "low", "medium", "high", "max"]

[[reasoning_options]]
type = "budget_tokens"

[cost]
input = 0.2475
output = 1.485
cache_read = 0.02475
cache_write = 0.082497

[[cost.tiers]]
tier = { type = "context", size = 200_000 }
input = 0.495
output = 2.2275
cache_read = 0.02475
cache_write = 0.082497

[limit]
output = 65_535
