base_model = "google/gemini-3.1-flash-lite"

[[reasoning_options]]
type = "effort"
values = ["none", "low", "medium", "high", "max"]

[[reasoning_options]]
type = "budget_tokens"

[cost]
input = 0.225
output = 1.35
cache_read = 0.0225
cache_write = 0.074997

[[cost.tiers]]
tier = { type = "context", size = 200_000 }
input = 0.45
output = 2.025
cache_read = 0.0225
cache_write = 0.074997

[limit]
output = 65_535
