base_model = "minimax/MiniMax-M3"
name = "MiniMax-M3 (EU)"
structured_output = true

[[reasoning_options]]
type = "effort"
values = ["none", "low", "medium", "high", "max"]

[[reasoning_options]]
type = "budget_tokens"

[cost]
input = 0.36
output = 1.8
cache_read = 0.09

[limit]
output = 1_048_576
